// Mock data — single source of truth for the prototype.
window.NoreonData = {
  user: {
    name: "Mira",
    email: "mira@noreon.health",
    age: 34,
    sex: "Female",
    height: 168, // cm
    weight: 64,  // kg
    city: "Lisbon",
    work: "Hybrid, 9–18",
    goals: ["Energy", "Sleep", "Metabolism", "Longevity"],
    conditions: [],
    medications: ["Vitamin D · 1000 IU daily"],
    allergies: ["Penicillin"],
    supplements: ["Magnesium glycinate", "Omega-3"],
    family: ["Heart (paternal)", "Thyroid (maternal)"],
    rhythm: {
      wake: "07:00",
      bed:  "23:30",
      workHours: "9–18",
      sittingHrs: 8,
      mealTiming: "Lunch 13:00, Dinner 20:30",
    },
    nutrition: {
      style: "Omnivore",
      restrictions: ["Lactose-light"],
      cravings: "Sugar in late afternoons",
      eatingOut: "2× / week",
      challenge: "Snacking after work",
    },
    sleep: {
      duration: 7.1,
      quality: "Good",
      consistency: "Mostly",
      caffeineCutoff: "14:00",
      screenUse: "Light, before bed",
    },
    movement: {
      current: "Walks + light yoga",
      stepBaseline: 6400,
      limitations: "None",
      access: "Gym + home",
    },
    stress: { level: 3, barrier: "Time pressure", style: "Calm, practical" },
    wellbeing: { /* optional, left empty by default */ },
  },
  zoeOrbColors: ["coral", "twilight", "sage", "blush", "lilac"],
  starterRoutine: [
    { id: "morning", title: "Morning", orb: "blush",
      lines: ["Wake by 07:00 — open the curtains immediately.",
              "500ml of water before coffee.",
              "Three slow minutes of stretching or stairs."] },
    { id: "food", title: "Food", orb: "sage",
      lines: ["Breakfast: protein-led. Eggs, yogurt, or beans.",
              "Lunch: vegetables fill half the plate.",
              "Dinner: finish three hours before bed."] },
    { id: "walking", title: "Walking", orb: "coral",
      lines: ["Daily target: 7,500 steps.",
              "A twelve-minute walk after lunch is enough."] },
    { id: "exercise", title: "Exercise", orb: "twilight",
      lines: ["Two strength sessions per week (30 min).",
              "One mobility flow on rest days.",
              "Substitute a walk on tired days — no guilt."] },
    { id: "sleep", title: "Sleep", orb: "lilac",
      lines: ["Wind-down window 22:30 — dim the lights.",
              "Caffeine cutoff 14:00.",
              "Phone outside the bedroom on weeknights."] },
    { id: "stress", title: "Stress", orb: "blush",
      lines: ["Three minutes of box-breathing before lunch.",
              "One walk without your phone each day."] },
  ],
  todayMissions: [
    { id: "m1", type: "Food", orb: "sage", text: "Protein-led breakfast (25g+).", done: true },
    { id: "m2", type: "Walking", orb: "coral", text: "Twelve-minute walk after lunch.", done: false },
    { id: "m3", type: "Sleep", orb: "lilac", text: "Caffeine off after 14:00.", done: false },
    { id: "m4", type: "Stress", orb: "blush", text: "Three minutes of box-breathing.", done: false },
  ],
  rhythmTiles: [
    { id: "walking", label: "Walking", days: [1,1,1,0.5,1,1,0], pct: 78 },
    { id: "sleep",   label: "Sleep",   days: [1,1,0,1,1,1,0.5], pct: 82 },
    { id: "food",    label: "Food",    days: [1,1,1,1,1,1,0], pct: 86 },
    { id: "stress",  label: "Stress",  days: [0.5,1,0,1,1,0,0], pct: 50 },
  ],
  weekFocus: {
    title: "Metabolic Rhythm",
    sub: "A week of steady fuel and gentle movement.",
    missions: [
      { id: "w1", text: "Protein at breakfast, four days.",     progress: 0.75 },
      { id: "w2", text: "A walk after the largest meal, daily.", progress: 0.6 },
      { id: "w3", text: "Last meal three hours before bed.",     progress: 0.8 },
      { id: "w4", text: "One alcohol-free evening.",             progress: 1 },
    ],
    targetCopy: "Most weeks land between 60% and 80%. That is enough.",
  },
  testPackage: {
    name: "Foundation Panel",
    positioning: "The first conversation between your body and your routine.",
    categories: [
      "Metabolic", "Lipid panel", "Inflammation", "Hormonal",
      "Thyroid", "Kidney function", "Liver function", "Vitamins & minerals",
      "Complete blood count", "Iron studies",
    ],
    reasons: [
      { orb: "coral",    title: "It turns guesses into signal",
        body: "Your routine adjusts to what your body actually shows, not what you assume." },
      { orb: "sage",     title: "A clinician reads every result",
        body: "Findings are reviewed by a doctor before they reach you, in plain language." },
      { orb: "twilight", title: "It becomes a habit, not a verdict",
        body: "Retest in six months and watch what your changes did. Trends matter more than one number." },
    ],
  },
  testStatuses: [
    { id: "selected",   title: "Package selected",         when: "Mon, 18 May · 17:00", note: "You chose the Advanced Biomarker Panel. Twenty-six markers across seven categories.", voice: null },
    { id: "scheduled",  title: "Visit scheduled",          when: "Mon, 18 May · 17:12", note: "Booking confirmed for Tuesday 08:30. A preparation reminder will arrive the night before.", voice: null },
    { id: "collected",  title: "Blood sample collected",   when: "Tue, 19 May · 08:54", note: "Joana, your phlebotomist, completed the draw. Sample en route to the lab.", voice: "Well done. The hardest minute is over." },
    { id: "processing", title: "Lab analysis in progress", when: "Wed, 20 May · 11:10", note: "Twenty-six assays running across two analyzers. Results usually return within 48 hours.", voice: null },
    { id: "review",     title: "Doctor review in progress", when: "Thu, 21 May · 14:25", note: "Dr. Almeida is reading your results now — checking for context your numbers don't show on their own.", voice: "A clinician is reading your results now. We're almost there." },
    { id: "ready",      title: "Results ready",            when: "Thu, 21 May · 18:02", note: "Reviewed and released. Your biomarker dashboard is open.", voice: null },
    { id: "ai",         title: "AI interpretation available", when: "Thu, 21 May · 18:04", note: "Zoe has read every line of your report. Tap any biomarker or recommendation and she will explain.", voice: "Your report is ready. We'll walk through it together." },
  ],
  report: {
    reviewedBy: "Dr. Inês Almeida, MD",
    reviewedOn: "21 May 2026",
    headline: "Your metabolic rhythm is asking for a gentler week.",
    executive:
      "Most of your foundation reads steady — sleep, liver, and kidney markers all sit comfortably inside healthy ranges. Two patterns suggest your body is moving faster than your recovery: an elevated fasting glucose, and a borderline inflammatory marker. Neither is alarming. Both respond well to small daily changes.",
    strong: [
      "Lipid profile is balanced. HDL is generous for your age.",
      "Liver and kidney markers are unremarkable.",
      "Vitamin D arrived at a healthy 38 ng/mL.",
    ],
    watch: [
      { level: "watch", text: "Fasting glucose 102 mg/dL — a watch-level pattern, not a diagnosis." },
      { level: "watch", text: "hs-CRP 2.4 mg/L — mild inflammation. Often lifestyle-responsive." },
      { level: "low",   text: "Ferritin trending low — within range, but worth watching at retest." },
    ],
    biomarkers: [
      { name: "Fasting glucose",  category: "Metabolic",       value: 102, previous: 96,  unit: "mg/dL", low: 70,  high: 99,  flag: "watch" },
      { name: "HbA1c",            category: "Metabolic",       value: 5.4, previous: 5.3, unit: "%",     low: 4.0, high: 5.6, flag: "ok" },
      { name: "LDL cholesterol",  category: "Cardiovascular",  value: 108, previous: 118, unit: "mg/dL", low: 0,   high: 130, flag: "ok" },
      { name: "HDL cholesterol",  category: "Cardiovascular",  value: 64,  previous: 62,  unit: "mg/dL", low: 50,  high: 100, flag: "ok" },
      { name: "Triglycerides",    category: "Cardiovascular",  value: 88,  previous: 102, unit: "mg/dL", low: 0,   high: 150, flag: "ok" },
      { name: "hs-CRP",           category: "Inflammation",    value: 2.4, previous: 1.6, unit: "mg/L",  low: 0,   high: 1.0, flag: "watch" },
      { name: "Ferritin",         category: "Iron studies",    value: 28,  previous: 38,  unit: "ng/mL", low: 25,  high: 200, flag: "low" },
      { name: "TSH",              category: "Thyroid",         value: 1.8, previous: 2.1, unit: "mIU/L", low: 0.4, high: 4.0, flag: "ok" },
      { name: "Vitamin D",        category: "Vitamins & minerals", value: 38, previous: 28, unit: "ng/mL", low: 30, high: 80,  flag: "ok" },
    ],
    plan: [
      "Lead breakfast with protein, four days a week.",
      "Walk twelve minutes after your largest meal.",
      "One alcohol-free evening, every week.",
      "Iron-rich food twice a week — eggs, lentils, leafy greens.",
      "Retest the foundation panel in six months.",
    ],
    recommendations: {
      "30": {
        eyebrow: "Next 30 days",
        title: "Quiet, daily changes.",
        sub: "What we change first — and what we leave alone.",
        items: [
          { icon: "Food",     text: "Lead breakfast with 25–30g of protein, four days a week." },
          { icon: "Walking",  text: "A twelve-minute walk after your largest meal." },
          { icon: "Sleep",    text: "Caffeine cutoff at 14:00, every weekday." },
          { icon: "Food",     text: "Iron-rich meal twice a week — eggs, lentils, leafy greens." },
          { icon: "Stress",   text: "One alcohol-free evening, every week." },
        ],
      },
      "60": {
        eyebrow: "Day 30 → 60",
        title: "Build on the steady week.",
        sub: "Now we layer. Same shape, slightly more rhythm.",
        items: [
          { icon: "Exercise", text: "Add a second strength session — 25 minutes, lower body." },
          { icon: "Walking",  text: "Walk after both lunch and dinner, four days a week." },
          { icon: "Food",     text: "Photograph one meal a day so Zoe can read the week." },
          { icon: "Sleep",    text: "Move bedtime to 23:00 — your earliest possible without strain." },
        ],
      },
      "90": {
        eyebrow: "Day 60 → 90",
        title: "Retest, and read what changed.",
        sub: "We measure again. The numbers will tell us what your changes did.",
        items: [
          { icon: "Lab",      text: "Schedule a Foundation retest, fasting morning slot." },
          { icon: "Food",     text: "Confirm the protein-led breakfast as a permanent habit." },
          { icon: "Doctor",   text: "If hs-CRP remains above 2 mg/L, your clinician suggests a metabolic deep-dive panel." },
          { icon: "Stress",   text: "Choose one stress signal to track in the next 90 days — sleep, mood, or recovery." },
        ],
      },
    },
    followup: "No specialist referral needed. We will revisit ferritin and hs-CRP at your six-month retest.",
  },

  // ── Multiple lab packages ────────────────────────────────────
  labPackages: [
    {
      id: "essential", name: "Essential Health Check", orb: "blush",
      designedFor: "First-timers building a baseline.",
      sub: "A short, honest snapshot.",
      blurb: "Twelve foundational markers — enough to know whether the rest of your year needs adjusting.",
      categories: ["Metabolic", "Lipid panel", "Liver function", "Kidney function", "Complete blood count"],
      biomarkerCount: 12,
      price: 89, recommended: false,
    },
    {
      id: "foundation", name: "Advanced Biomarker Panel", orb: "coral",
      designedFor: "Curious, careful generalists.",
      sub: "The most-chosen panel.",
      blurb: "Our flagship foundation. Twenty-six markers covering metabolic, lipid, inflammation, thyroid, hormonal and nutritional signals.",
      categories: ["Metabolic", "Lipid panel", "Inflammation", "Thyroid", "Vitamins & minerals", "Hormonal", "Iron studies"],
      biomarkerCount: 26,
      price: 189, recommended: true,
    },
    {
      id: "longevity", name: "Longevity & Prevention Panel", orb: "twilight",
      designedFor: "Long-horizon thinkers.",
      sub: "Slower-moving signals.",
      blurb: "Adds advanced lipid subfractions, ApoB, homocysteine, and inflammation patterns associated with healthspan.",
      categories: ["ApoB", "Lp(a)", "Homocysteine", "Advanced lipid", "Inflammation", "HbA1c", "Vitamins"],
      biomarkerCount: 34,
      price: 269, recommended: false,
    },
    {
      id: "metabolic", name: "Metabolic Health Panel", orb: "sage",
      designedFor: "Energy, weight, and glucose questions.",
      sub: "Focused on metabolism.",
      blurb: "Fasting insulin, glucose, HbA1c, full lipid sub-panel, liver enzymes, and inflammation in one read.",
      categories: ["Fasting insulin", "Glucose", "HbA1c", "Lipid panel", "Liver function", "Inflammation"],
      biomarkerCount: 18,
      price: 149, recommended: false,
    },
    {
      id: "womens", name: "Women's Health Panel", orb: "lilac",
      designedFor: "Cycle, energy, and hormonal balance.",
      sub: "Hormonally aware.",
      blurb: "Full thyroid, ferritin, oestradiol, progesterone, FSH, LH, prolactin, vitamin D, plus the metabolic foundation.",
      categories: ["Thyroid", "Sex hormones", "Iron studies", "Vitamins", "Metabolic"],
      biomarkerCount: 24,
      price: 199, recommended: false,
    },
    {
      id: "mens", name: "Men's Health Panel", orb: "amber",
      designedFor: "Energy, recovery, and hormonal balance.",
      sub: "Hormonally aware.",
      blurb: "Total + free testosterone, SHBG, PSA, full thyroid, iron studies, plus the metabolic foundation.",
      categories: ["Testosterone", "Thyroid", "PSA", "Iron studies", "Metabolic"],
      biomarkerCount: 22,
      price: 199, recommended: false,
    },
    {
      id: "premium", name: "Premium Full Body Insight", orb: "storm",
      designedFor: "The whole picture, at depth.",
      sub: "Our deepest read.",
      blurb: "Everything in the Advanced and Longevity panels, plus extended hormonal, vitamin and mineral profiles.",
      categories: ["All categories", "Advanced lipid", "Hormonal", "Longevity markers", "Inflammation", "Full vitamins"],
      biomarkerCount: 52,
      price: 349, recommended: false,
    },
  ],

  // ── Glossary — what Zoe says when a biomarker is tapped ───────
  biomarkerGlossary: {
    "Fasting glucose":
      "The amount of sugar circulating in your blood after an overnight fast. It tells us how readily your body returns to baseline between meals. A single high reading is rarely the whole story — we look at it next to HbA1c, which averages the last three months.",
    "HbA1c":
      "A three-month average of your blood sugar. Because red blood cells live about 90 days, HbA1c gives us a steadier picture than a single morning glucose reading. Small changes here are slow changes — that's a good thing.",
    "LDL cholesterol":
      "Often called the carrier cholesterol. Higher numbers, sustained over years, are associated with cardiovascular risk. Yours is in a healthy range and trending down — your changes are working.",
    "HDL cholesterol":
      "The protective cholesterol — generally we want this higher rather than lower. Yours is generous for your age, which is genuinely good news.",
    "Triglycerides":
      "Circulating fats your body uses for energy. Sensitive to recent meals and alcohol. Yours is well inside range.",
    "hs-CRP":
      "A sensitive marker of inflammation throughout the body. It rises with infection, poor sleep, intense stress, and metabolic strain. Yours is mildly elevated — a watch-level pattern, often very responsive to lifestyle.",
    "Ferritin":
      "Your body's iron store. Within range here, but trending downward. We'll keep watching it — and add iron-rich meals twice a week.",
    "TSH":
      "Thyroid-stimulating hormone, the conductor of your metabolism. Yours sits comfortably in range.",
    "Vitamin D":
      "A hormone-like nutrient that supports bone, immune and metabolic health. Yours improved meaningfully since your last test — sunlight and supplementation are doing their work.",
  },

  zoeSuggestedQuestions: [
    "Explain my biomarkers",
    "Ask about my results",
    "Create my 30-day health plan",
    "What should I improve first?",
    "How does the blood draw work?",
  ],
};
